### PR TITLE
feat(react-arrays): add exercise 01

### PR DESCRIPTION
**Pull request by pixelass**
Migrated from https://codesandbox.io/s/react-arrays-exercise-fruits-start-1ht6lf

### CODE REVIEW

**Review by PReichetanz — CHANGES_REQUESTED** [review]
[Within our exercises for this session](https://github.com/neuefische/web-pool-2022/blob/main/sessions/react-arrays/exercises.md), this is the Codesandbox for exercise 2, but is called here exercise 1 (and vice versa for the other PR).

**Comment by pixelass** [comment]
> [Within our exercises for this session](https://github.com/neuefische/web-pool-2022/blob/main/sessions/react-arrays/exercises.md), this is the Codesandbox for exercise 2, but is called here exercise 1 (and vice versa for the other PR).

Good catch. I'll change the folder names for both exercises.

**Comment by pixelass** [comment]
@PReichetanz I updated the folder

**Review by PReichetanz — APPROVED** [review]
I think the exercise works as expected, [see my solution here](https://codesandbox.io/s/modest-frost-3ti9kd?file=/src/App.js).

**Pull request merged**
